/* 
 * $Id: h-insert.h,v 1.1 2001/01/30 16:39:12 dimka Exp $
 *
 * $Log: h-insert.h,v $
 * Revision 1.1  2001/01/30 16:39:12  dimka
 * Some old and modified packages
 *
 *
 * This file is part of %U's private collection.
 * Copyright (c) %y. %a. 
 * %o
 *
 * %f -- %[Describe: %]
 *
 */

#ifndef _%b_%e_
#define _%b_%e_

%@

#endif

/* 
 * Local Variables:
 * compile-command: "make %b.o"
 * End:
 */


